docs: item store on @ControllerConfiguration
operator-framework/java-operator-sdk pull request #1942
Opened 2023-06-14 08:35 UTC by csviri

2023-06-15 21:47 UTC, metacosm requested changes
The documentation is incorrect. This is a simple copy and paste from the related ResourceConfiguration method. While the two methods are similar, they do not have the exact same behavior and therefore deserve appropriate documentation. Also, the links here and in ResourceConfiguration regarding the CaffeineBoundedCache are wrong.

2023-06-19 15:54 UTC, metacosm requested changes
Still incorrect.

2023-06-19 16:34 UTC, csviri commented
What exactly? @metacosm

2023-06-20 07:24 UTC, metacosm approved these changes

2023-06-20 07:27 UTC, merged