feat: add default delete condition to managed dependent resources
operator-framework/java-operator-sdk pull request #2183
Opened 2024-01-04 09:49 UTC by csviri

2024-01-05 16:44 UTC, stevekuznetsov reviewed
Are you able to use ObjectReferences to allow k8s to do the cascading deletion for you?

2024-01-05 17:31 UTC, csviri commented
Hi @stevekuznetsov , KubernetesDependentResource handle owner references by default for you, this can be cusotmized also in multiple ways. See: https://javaoperatorsdk.io/docs/dependent-resources#telling-josdk-how-to-find-which-secondary-resources-are-associated-with-a-given-primary-resource

See also [`GarbageCollected`](
https://github.com/java-operator-sdk/java-operator-sdk/blob/16066ea738a33a9577bf84bc07a82a9a2e01582a/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/GarbageCollected.java#L28-L28) interface docs.

2024-01-08 20:49 UTC, metacosm requested changes

2024-01-08 20:49 UTC, metacosm commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/KubernetesResourceDeletedCondition.java
> +public class KubernetesResourceDeletedCondition implements Condition<HasMetadata, HasMetadata> {
This needs to be better documented.

2024-01-08 20:49 UTC, metacosm commented on docs/documentation/workflows.md
> +calls delete on resource, in case it uses a finalizer, it should be checked by a `DeletePostCondition` if it
This isn't really clear and should be better explained, as it's not clear why having a finalizer changes things and why a delete post condition is needed.

2024-01-09 12:10 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/KubernetesResourceDeletedCondition.java
> +public class KubernetesResourceDeletedCondition implements Condition<HasMetadata, HasMetadata> {
added javadoc

2024-01-09 15:23 UTC, merged