Ssa finalizer resource updates
operator-framework/java-operator-sdk pull request #2305
Opened 2024-03-21 12:11 UTC by csviri

2024-03-27 13:42 UTC, csviri commented
@metacosm this is the implementation so far, will add integration test and docs that explains stuff but might worth to take a look on it now, if everything makes sense

2024-03-28 14:54 UTC, csviri commented
@metacosm this PR is ready for review, the docs updates are missing only, will add it soon

2024-04-05 12:24 UTC, metacosm requested changes

2024-04-08 08:28 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcher.java
> +      P resource = (P) originalResource.getClass().getConstructor().newInstance();
Hmm, good point, will try it with `GenericKubernetesResource`

2024-04-08 08:32 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventProcessor.java
> -      postExecutionControl
This works only if the patch is with optimistic locking, but now neither of the patches do. Mainly for default SSA it definitely should not be, but we should not press it probably for non-SSA either.

2024-04-08 08:54 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcher.java
> +      P resource = (P) originalResource.getClass().getConstructor().newInstance();
Took a look but all our API-s work with typed API. Added a better message. Maybe we could try to optimize in a separate PR?
Also would not worry to much about performance, this only happens once, when the resource is created, on on every reconciliation.

2024-04-08 13:05 UTC, merged