chore: adjust debug logs for updating a dependent resource
operator-framework/java-operator-sdk pull request #2428
Opened 2024-06-06 05:48 UTC by matteriben

Moved existing debug log message and added new debug log message.

2024-06-06 06:32 UTC, csviri requested changes

2024-06-06 06:32 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/AbstractDependentResource.java
> +                actualResource);
Let's not log the whole resources, this is a security concern, to not log secrets, thus sensitive data.

2024-06-06 18:57 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/AbstractDependentResource.java
> +              getClass().getSimpleName());
Probably would be better to put here also the resource ID.

2024-06-07 07:14 UTC, csviri approved these changes

2024-06-07 11:36 UTC, metacosm approved these changes
We should use the dependent name in `next` as well.

2024-06-07 11:36 UTC, merged